### ISSUE TITLE
Ability to dismiss overlay messages

### ISSUE THREAD

**Issue by tavvy** [Financial-Times/n-swg#44]
Currently the user cannot dismiss the overlay messages. They should be able to click away, or press escape, maybe even have a cross icon.

<img width="1276" alt="screen shot 2018-04-25 at 12 14 14" src="https://user-images.githubusercontent.com/660635/39242561-4335ce04-4882-11e8-91b0-9999e386f353.png">

**Comment by remybach** [comment]
Merged and deployed.
