### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by tavvy** [Financial-Times/n-swg#49]
- `landing` upon the subscribe flow starting
- `success` upon successful buy flow

**Comment by remybach** [comment]
PR here: https://github.com/Financial-Times/n-swg/pull/50

**Comment by remybach** [comment]
It should be noted that `success` is already tracked here: [swg-controller.js:133](https://github.com/Financial-Times/n-swg/blob/rb-update-tracking/src/client/swg-controller.js#L133)

**Comment by remybach** [comment]
Merged and deployed.
